version: '2.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - develop_MoveWcfToApi 
# Do not build on tags (GitHub and BitBucket)
skip_tags: true
  
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  
build:
  # enable MSBuild parallel builds
  parallel: false
  # path to Visual Studio solution or project      
  #project: Horsify 2.0.sln
  
before_build:
  # Display .NET Core version  
  - cmd: dotnet --version
  - nuget restore "src/Horsify 2.0.sln"  
  # Display minimal restore text
  # - ps: .\Services\Horsesoft.Music.Horsify.Api\build.ps1
  # - cmd: dotnet restore ./Data/Horsesoft.Music.Data.Model/Horsesoft.Music.Data.Model.csproj --verbosity m
  # - cmd: dotnet restore ./Data/Horsesoft.Music.Data.Sqlite/Horsesoft.Music.Data.Sqlite.csproj --verbosity m
  # - cmd: dotnet restore ./Repo/Horsesoft.Music.Horsify.Repositories/Horsesoft.Music.Horsify.Repositories.csproj --verbosity m
  # - cmd: dotnet restore ./Tests/Horsesoft.Music.Horsify.RepositoryTests/Horsesoft.Music.Horsify.RepositoryTests.csproj --verbosity m  
  # - cmd: dotnet restore ./Tests/Horsesoft.Music.EngineTests/Horsesoft.Music.EngineTests.csproj --verbosity m      


  
# build cache to preserve files/folders between builds
cache:
  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages -> **\packages.config
  - projectA\libs
  #- node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3  

# Build platforms
platform:
  - x64
# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release
  - Debug
  
matrix:
  exclude:
    - configuration: Debug 
    
test: off
# test:
  # # except assemblies to test
  # assemblies:
    # except:
      # - '**\bin\$(configuration)\*Tests.dll'    

build_script:
- ps: .\build.ps1
- ps: .\src\Services\Horsesoft.Music.Horsify.Api\build.ps1
  
after_build:
  # For once the build has completed
artifacts:
    - path: '\Installer\Horsify.Installer\bin\x64\Release\Horsify.Installer.msi'
      name: HorsifyInstallerX64
    - path: '\Installer\Horsify.Installer\bin\x86\Release\Horsify.Installer.msi'
      name: HorsifyInstallerX86
clone_depth: 1
on_finish :
deploy: off
